x-api: &api
  platform: linux/amd64
  image: ${RINHA_API_IMAGE:-docker.io/rodrigodotdev/rinha-backend-2026-bun-zig:latest}
  restart: always
  volumes:
    - sock:/run/sock
  deploy:
    resources:
      limits:
        cpus: "0.4"
        memory: "150M"

services:
  api-1:
    <<: *api
    environment:
      SOCKET_PATH: /run/sock/api-1.sock
      WARMUP_ROUNDS: ${WARMUP_ROUNDS:-16}

  api-2:
    <<: *api
    environment:
      SOCKET_PATH: /run/sock/api-2.sock
      WARMUP_ROUNDS: ${WARMUP_ROUNDS:-16}

  lb:
    platform: linux/amd64
    image: haproxy:alpine
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sock:/run/sock
    ports:
      - "9999:9999"
    depends_on:
      - api-1
      - api-2
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30M"

volumes:
  sock:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=16m,mode=1777
